#include <iostream>
#include <string>



using namespace std;

int main()
{


    int num1;
    int num2;
    int opr;
    cout << "enter first number";
    cin >> num1;
    cout << "Enter a second number";
    cin >> num2;
    cout << "Enter your operator";
    cin >> opr;

    if (opr = '+')
    {
        cout << num1 + num2;
    }
    if (opr = '-')
    {
        cout << num1 - num2;
    }
    if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
       if (opr = '+')
    {
        cout << "Cock";
    }
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";
cout << "I love people";

}